### ISSUE TITLE
Use nv-codec-headers to load cuda and nvdec

### ISSUE THREAD

**Issue by philipl** [elFarto/nvidia-vaapi-driver#1]
The best way to work with cuda and nvdec is to use [nv-codec-headers](https://git.videolan.org/?p=ffmpeg/nv-codec-headers.git) and the dynamic loader it provides. This makes it much easier to build and distribute binaries. Of course, the wacky eglstream interop methods will need to be added, but that's relatively simple.

I'll put together a PR when I get a chance.

**Comment by elFarto** [comment]
Merged! Thanks for the patch.
