### ISSUE TITLE
Q: VA-API driver documentation

### ISSUE THREAD

**Issue by mar0x** [elFarto/nvidia-vaapi-driver#105]
Hello.
I'm unable to find the documentation for VA-API user space driver developers. Is there is a something like OpenMAX IL Specification? Could you please share the documentation you are using.

**Comment by elFarto** [comment]
I've not found any documentation for VA-API driver developers, as far as I can tell none exists. I worked out what to do by looking at the other open source drivers and lots of trial and error.

**Comment by mar0x** [comment]
Thanks for reply!

> I worked out what to do by looking at the other open source drivers and lots of trial and error.

Yes, it seems to be the only source. But someone have created those open source drivers before! :)

Best regard and happy sources digging,
Max
