### ISSUE TITLE
Deprecated "mpv" debug option "--opengl-debug" be replaced by "--gpu-debug"

### ISSUE THREAD

**Issue by ManuLinares** [elFarto/nvidia-vaapi-driver#106]
https://github.com/elFarto/nvidia-vaapi-driver/blob/8e66a2fe429a57fda1bbd735842fe8fec87d1d7b/test.sh#L21

`[cplayer] Warning: option --opengl-debug was replaced with --gpu-debug and might be removed in the future.`

should be: `$MPV -v --msg-level=all=debug --hwdec=vaapi --gpu-debug --hwdec-codecs=all --vd-lavc-check-hw-profile=no "$@"`

**Comment by elFarto** [comment]
I hadn't noticed that warning before. I'll update the option when I get a moment.

**Comment by elFarto** [comment]
Finally got around to fixing this.
