### ISSUE TITLE
How to find out that it works?

### ISSUE THREAD

**Issue by rubyFeedback** [elFarto/nvidia-vaapi-driver#117]
I just compiled the latest git source of nvidia-vaapi-driver.

No error was reported.

But how do I know it works?

Trying to use "nvidia-settings" from the commandline does not
show anything. There is also no example for mpv. Could you
perhaps add a bit more documentation here? Ideally also some
way to test that things may work now?

I found this project by a recommendation from reddit, also due
to my nvidia card having problems so I was hoping perhaps
this can help. But I am a bit lost what to do ... Making this
more explicit in the main README would be super-helpful.

**Comment by elFarto** [comment]
There's a section at the bottom of the README that details how to verify if it's working.

**Comment by pc00per** [comment]
Tbh. You should open a discussion thread on this repo. QnA shouldn't be asked in the issues.
