### ISSUE TITLE
Tag official release containing e94663c6ca to fix uninitialized memory usage

### ISSUE THREAD

**Issue by cgutman** [elFarto/nvidia-vaapi-driver#118]
Sorry for the "not really a bug report" issue, I didn't find a better medium to communicate this.

I am using the RPM Fusion packaged version of `nvidia-vaapi-driver` for Fedora, which is currently based on `0.0.6` tag. I am experiencing very frequent segmentation faults calling `vaInitialize()` in [moonlight-qt](https://github.com/moonlight-stream/moonlight-qt) (likely because Moonlight regularly reinitializes `libva` in the same process, making the crash significantly more likely to occur).

Since Moonlight probes for VAAPI hardware decoding support as part of startup and `libva` now has a VAAPI driver mapping for `nvidia-drm`, it quite often just makes it crash outright on any NVIDIA system with `nvidia-vaapi-driver` installed.

The uninitialized memory usage bug was fixed in e94663c6ca and works wonderfully in Moonlight, but most (all?) distros haven't picked up the fix since it hasn't made it into an official release yet. Would you mind tagging a new release containing this fix to help get the fixes into downstream packages?

**Comment by elFarto** [comment]
Yep, it does seem time for a release. I've tagged and released v0.0.7 with that fix.
