### ISSUE TITLE
GT740 acceleration is (seemingly?) not working.

### ISSUE THREAD

**Issue by Impeta** [elFarto/nvidia-vaapi-driver#119]
![Screenshot_20221015_171756](https://user-images.githubusercontent.com/105376276/196006089-6415b53b-eff6-4423-8f77-2098a3801c56.png)
My env. variables for Firefox: `GTK_CSD=1 NVD_LOG=1 MOZ_X11_EGL=1 LIBVA_DRIVER_NAME=nvidia MOZ_DISABLE_RDD_SANDBOX=1 firefox %u`
I made sure all the necessary tweaks to do on `about:config` are done, exception being `EGL_PLATFORM` since I only run X11. Oddly enough, my nvidia-settings still shows only zero for `Video Engine Utilization`, yet `GPU Utilization` **does** report elevating percentage based on a Youtube video I play or not.

Inputting `vainfo` outputs this:
![Screenshot_20221015_174333](https://user-images.githubusercontent.com/105376276/196006829-b99e52b6-472e-45f3-93f4-82c138de981e.png)

- EndeavourOS (Arch Linux), Firefox 105.0.3.

**Comment by elFarto** [comment]
Can you run that test again with `MOZ_LOG='PlatformDecoderModule:5,Dmabuf:5'` set?

**Comment by elFarto** [comment]
That error is normal. Given that you're attempting to play back a Youtube video on a 740, the issue is almost certainly that it's attempting to play a VP9 video, which can't be accelerated by your card. The [h264ify](https://addons.mozilla.org/en-GB/firefox/addon/h264ify/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search) add-on can force Youtube to only use specific codecs (there are other add-ons that do similar things).

**Comment by elFarto** [comment]
Ok, can you post another log with MOZ_LOG set?

**Comment by elFarto** [comment]
Can you upload the full log, from when Firefox starts?

**Comment by elFarto** [comment]
You can use something like `... firefox |& tee output.log` if you're using bash. This will print it to the terminal, and log it to `output.log` in the current directory.

Could you also upload the output of `eglinfo` too, there's something in that first log you sent me that's concerning me.

**Comment by elFarto** [comment]
It looks like it's half working now, it's decoding the video with VA-API but it's unable to import the frame into EGL. And that's likely due to Firefox using the MESA EGL driver, not the NVIDIA one. Can you check the `about:support` page in Firefox?, and have a look at the `GPU #1` section.

**Comment by elFarto** [comment]
That looks good. Note that `LIBVA_DRIVER_NAME=nvidia` only effects which driver VA-API picks, not what EGL implementation Firefox gets. I'm still digging into why Firefox is doing this, but this issue looks related to the 470 driver not implementing the `EGL_EXT_device_drm_render_node` EGL extension causing it to pick up a different (incorrect) EGL implementation.

**Comment by elFarto** [comment]
Can you check to see if you have this file `/usr/share/glvnd/egl_vendor.d/50_mesa.json`. If you do, try removing it (copy it to your home directory for safe keeping) and try again.

**Comment by elFarto** [comment]
Excellent, I'll add a note to the README about that.

The 50_mesa.json file adds the MESA EGL driver to glvnd's list of drivers (glvnd being the main EGL library that then loads the gfx driver specific implementations). Without it you won't be able to use any MESA devices (Intel, AMD or nouveau), or the software renderer. However that shouldn't be a problem for you.

You may need to keep an eye on that file, as whatever package owns it might replace it at some point. Your distro might have an option to permanently remove it.

Given you have an older card with low VRAM, the NVD_MAX_INSTANCES option may be worth looking at if you get any problems with video heavy sites.

**Comment by jp7677** [comment]
Just a shot in the dark, but does setting `__EGL_VENDOR_LIBRARY_FILENAMES=/usr/share/glvnd/egl_vendor.d/10_nvidia.json` instead of removing `50_mesa.json` fixes this too? This with the assumption that `10_nvidia.json` exists in that path on your system.

**Comment by elFarto** [comment]
From my quick test, it looks like setting that environment variable will have the same effect as removing the `50_mesa.json` file.
