### ISSUE TITLE
Unable to set `nvidia-drm.modeset=1` using Optimus for hybrid GPU hardware (NVIDIA Prime Offload)

### ISSUE THREAD

**Issue by Max-Rodriguez** [elFarto/nvidia-vaapi-driver#123]
I'm unable to use this driver because configuring the nvidia-drm kernel module to use modeset crashes my system. Had to manually recover the system via a live USB. Is there a way to get this working on NVIDIA Optimus systems that use both GPUs at once?

**Comment by elFarto** [comment]
In theory this driver works fine on an optimus system, assuming you run Firefox on the NVIDIA GPU. However, lots of people have had issues getting everything to play nicely together.

As for getting your distro to boot with modeset enabled, that's not something I can't help you with I'm afraid.
