### ISSUE TITLE
Availability Request: 0.0.8 on RPMFusion

### ISSUE THREAD

**Issue by cprin21** [elFarto/nvidia-vaapi-driver#143]
Version 0.0.7 is the latest version uploaded to the RPMFusion Nonfree repository, barring access to hardware acceleration for Fedora 37 users on Nvidia 525.

**Comment by elFarto** [comment]
I'm not the person who packages it for RPMFusion. You'd need to talk to the maintainer, @kwizart.

**Comment by kwizart** [comment]
Thanks for the report and mention.

FYI, the package for Fedora, RHEL and derivatives is located at https://github.com/rpmfusion/nvidia-vaapi-driver (github mirror)
And the preferred method to report issue is to use bugzilla.rpmfusion.org

**Comment by cprin21** [comment]
Thank you for your responses, I was unaware as the online browser of the repos didn't mention a listed maintainer and as such I defaulted to this github. Rightfully closed, glad to see a conclusive response!
