### ISSUE TITLE
Can't build / EGL missing (525-driver)

### ISSUE THREAD

**Issue by Michas0206** [elFarto/nvidia-vaapi-driver#161]
Hi, in short - 
I don't get it. How do I build nvidia-vaapi-driver with direct-backend - where do I have to set the environment-variable for "direct backend" exactly, or how?

Tried `export NVD_BACKEND=direct `and re-running "meson setup build" did not work, still the same Egl-error:

![Bildschirmfoto vom 2023-01-13 16-21-59](https://user-images.githubusercontent.com/29848666/212359659-c2fbc112-ff3b-4dfa-8a78-fecbef2e970b.png)

Many thanks in advance

**Comment by elFarto** [comment]
Both the `egl` and `direct` backend are built at compile time, you don't need to choose between them there. Only when running an application that makes use of VA-API, do you need to choose using the `NVD_BACKEND` environment variable.

The error you're getting is likely because you're missing the EGL development libraries/headers. This is provided by the `libglvnd-devel` package on my Fedora system, not sure what it'll be on your distro.

**Comment by Michas0206** [comment]
Many thanks, I'll check this and try it again later today.

Am 14. Januar 2023 10:53:34 UTC schrieb Stephen ***@***.***>:

**Comment by Michas0206** [comment]
Made some steps, build looked successful, but still without success....any ideas what I am missing?

![Bildschirmfoto vom 2023-01-14 17-27-30](https://user-images.githubusercontent.com/29848666/212483477-0f7efa24-c471-49f4-a88e-9e41a7152a29.png)
This setting was made to Grub and also updated Grub+restarted afterward:

![Bildschirmfoto vom 2023-01-14 17-29-15](https://user-images.githubusercontent.com/29848666/212483526-ce0e1f6a-f6e6-4483-b3ee-35eaf91ed7d4.png)

**Comment by elFarto** [comment]
Can you run firefox with `NVD_LOG=1 MOZ_LOG="Dmabuf:5,PlatformDecoderModule:5" firefox`? Do you have `MOZ_DISABLE_RDD_SANDBOX` set aswell?

**Comment by Michas0206** [comment]
Yes, MOZ_DISABLE_RDD_SANDBOX is 'true' currently.
![Bildschirmfoto vom 2023-01-14 17-40-53](https://user-images.githubusercontent.com/29848666/212484307-595d6bb4-eb37-488d-bb7a-63c144568dee.png)

**Comment by Michas0206** [comment]
Ah, I think I missed the part "In addition the following environment variables need to be set." - I set NVD_BACKEND only.....

**Comment by Michas0206** [comment]
Now with 
![Bildschirmfoto vom 2023-01-14 17-54-31](https://user-images.githubusercontent.com/29848666/212485112-8d2fef8f-5106-4549-94ea-a3612d0df241.png)
I get no error on startup anymore:
![Bildschirmfoto vom 2023-01-14 17-54-38](https://user-images.githubusercontent.com/29848666/212485127-83137352-53a5-46e8-b142-335cfa55cd45.png)

about:support now says
![Bildschirmfoto vom 2023-01-14 17-54-55](https://user-images.githubusercontent.com/29848666/212485174-6f08c5e0-0e42-42cc-9772-3ea02e2c4c97.png)

Is it active now? I'll try to figure out...

**Comment by Michas0206** [comment]
Hm, not sure, but blocklisted does not sound as "allowed" or everything is fine....

If I start firefox with your command from above now, it tells:
![Bildschirmfoto vom 2023-01-14 18-03-54](https://user-images.githubusercontent.com/29848666/212485712-ec6b65d7-4364-4d71-bd1e-87770d0ff11f.png)

**Comment by elFarto** [comment]
You've missed the N from `NVD_LOG`. However, I can see that it's failing to open /dev/dri/renderD128, which is possibly a permissions problem. You can try running `NVD_LOG=1 vainfo --display drm --device /dev/dri/renderD128`.

The about:support page is correct for when it's enabled. The wording on that page is confusing, but you're user pref is overriding the blocklist.

**Comment by Michas0206** [comment]
![Bildschirmfoto vom 2023-01-14 18-22-50](https://user-images.githubusercontent.com/29848666/212486770-07afea7a-85a0-4d75-b341-678f83cdf8ac.png)

**Comment by Michas0206** [comment]
Currently tried `NVD_LOG=1 MOZ_LOG="Dmabuf:5,PlatformDecoderModule:5" firefox` again:
![Bildschirmfoto vom 2023-01-14 18-24-58](https://user-images.githubusercontent.com/29848666/212486828-7ab69eea-d9d1-4861-8d24-36876ec17e9d.png)
and Ff is starting.

> The about:support page is correct for when it's enabled. The wording on that page is confusing, but you're user pref is overriding the blocklist.
Many thanks for your efforts, beside the "blocklisted" everything looks fine atm, I'll try around now a bit and play a bit with Firefox...

**Comment by elFarto** [comment]
Starting firefox when you already have a firefox window open will just cause that process to exit, so you need to make sure you exit all instances before you start another one from the command line.

**Comment by Michas0206** [comment]
Thanks, youre right: 
![Bildschirmfoto vom 2023-01-14 22-55-59](https://user-images.githubusercontent.com/29848666/212498884-97439923-72cb-4d1c-a6d5-5b5774c3e262.png)
