### ISSUE TITLE
exportMutex permanently locked state

### ISSUE THREAD

**Issue by 3331** [elFarto/nvidia-vaapi-driver#162]
exportMutex can end up in a permanently locked state when `reconnect` fails in `egl_allocateBackingImage` or if the `CHECK_CUDA_RESULT_RETURN` fails after succeding the `reconnect` call, this happens with the `test.sh` script in the repo.

**Comment by elFarto** [comment]
You're absolutely correct, thanks for pointing it out. The EGL backend hasn't been used much due to NVIDIA breaking it, so the issue hasn't been noticed.

I'll get a fix for that committed in soon.
