### ISSUE TITLE
direct and egl backends are not working

### ISSUE THREAD

**Issue by Monsterovich** [elFarto/nvidia-vaapi-driver#163]
**direct**
When using direct backend, I see green picture in mpv.
https://pastebin.com/iRtCvMFt

**egl**
Hardware decoding is just not working.
https://pastebin.com/zVLcMEX2

I'm using master branch.

NVIDIA GeForce RTX 3060 Ti
Driver: 525.78.01

**Comment by elFarto** [comment]
You need the latest version of mpv for it to work, 0.35.

**Comment by Monsterovich** [comment]
> You need the latest version of mpv for it to work, 0.35.

Could you write this in the README, please?

The hardware decoding, however, works in firefox.

`MOZ_DISABLE_RDD_SANDBOX=1 NVD_LOG=1 NVD_BACKEND=direct LIBVA_DRIVER_NAME=nvidia firefox`

The egl backend is broken too, yeah. :(
