### ISSUE TITLE
smplayer with mpv backend: audio work,but video gets green screen.

### ISSUE THREAD

**Issue by flwwater** [elFarto/nvidia-vaapi-driver#17]
Hi,develops:
    Firefox 97 nightly  works .
    smplayer + mpv backend: audio work,but video gets green screen.(use vaapi)
    gstreamer version: 1.18.5
    nvidia driver: 495.46

**Comment by elFarto** [comment]
A green screen in mpv usually means that you're not using the git master build of it. That is required as there's an issue with the latest released version.

**Comment by elFarto** [comment]
@flwwater Is it possible to test with the nightly build of mpv?

**Comment by elFarto** [comment]
I'm closing this issue, as it's almost certainly caused by not using the latest git version of mpv.
