### ISSUE TITLE
libgstreamer-plugins-bad1.0-0 dependency on Ubuntu 22.04

### ISSUE THREAD

**Issue by mcallaghan-geotab** [elFarto/nvidia-vaapi-driver#173]
Looks like https://packages.ubuntu.com/kinetic/amd64/nvidia-vaapi-driver/download , is 22.10; If we try to install manually on 22.04, there is an apt package dependency issue.
```
$ sudo dpkg -i ./nvidia-vaapi-driver_0.0.5-1_amd64.deb 
Selecting previously unselected package nvidia-vaapi-driver:amd64.
(Reading database ... 424449 files and directories currently installed.)
Preparing to unpack .../nvidia-vaapi-driver_0.0.5-1_amd64.deb ...
Unpacking nvidia-vaapi-driver:amd64 (0.0.5-1) ...
dpkg: dependency problems prevent configuration of nvidia-vaapi-driver:amd64:
 nvidia-vaapi-driver:amd64 depends on libgstreamer-plugins-bad1.0-0 (>= 1.20.2); however:
  Package libgstreamer-plugins-bad1.0-0 is not installed.

dpkg: error processing package nvidia-vaapi-driver:amd64 (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 nvidia-vaapi-driver:amd64
```

Does this _actually_ depend specifically/explicitly on that particular version of this package? It is highly unlightly systems will have that old version installed.

**Comment by philipl** [comment]
Why would you expect a package from 22.10 to install cleanly on 22.04? Also, your error says the package isn't installed - not that the version is incompatible. Invoking `dpkg` by itself won't install dependencies. You should use `apt install ./file.deb` which will pull in dependencies. Of course, that may well result in it telling you the 22.04 version of the dependency is too old. But such is life.
