### ISSUE TITLE
High power consumption with gnome wayland and mpv

### ISSUE THREAD

**Issue by sferi** [elFarto/nvidia-vaapi-driver#175]
Hi,

I'm using the latest nvidia driver in cachyos, running gnome on wayland, running mpv with --hwdec=vaapi-copy --vaapi-device=/dev/dri/renderD129 somefile.mp4 using the direct backend the video plays but powertop shows about 40-50 W consumption, NVD_LOG shows that the nvidia vaapi driver is used. nvidia vaapi version is compiled from latest git from AUR, on a dell xps 15 7590 optimus laptop. Changing gnome to X11 and using the prime-run mpv somefile.mp4 (h265 file) powertop shows around 30 W power consumption. Do you have any idea what might cause the higher power consumption of the nvidia vaapi driver?

Thank you
sferi

**Comment by Staudey** [comment]
See #74 for a discussion.
