### ISSUE TITLE
Random colors - hardware decoding - Firefox - v0.0.8 - Direct backend

### ISSUE THREAD

**Issue by VishalSubramanyam** [elFarto/nvidia-vaapi-driver#176]
System details: Kubuntu 22.10
NVIDIA driver version: 525.78

When I try to play YouTube videos on Firefox using the direct backend (since I'm using the 525 driver), I get random glitches in the videos (purples and pinks). I rolled back the NVIDIA driver to 515, and the problem stopped (presumably because it doesn't used the direct backend).

**Comment by elFarto** [comment]
Could you provide the log output of running `NVD_LOG=1 firefox` and playing a video that is corrupted? If you could post a screenshot of the corruption, that would be useful too. Also, which GPU do you have?
