### ISSUE TITLE
av1 support

### ISSUE THREAD

**Issue by krakow10** [elFarto/nvidia-vaapi-driver#18]
Testing on mpv with vaapi-copy, the other codecs work fine.  Playing av1 videos does report video decode in nvtop and the log prints the images decoded without any errors.  However, the output is corrupted:
![mpv-shot0015](https://user-images.githubusercontent.com/3529698/148499256-b86792c4-b851-4f14-9a35-9b5f3a4471b9.jpg)
I don't know where to begin looking for problems, what can I look for?

**Comment by krakow10** [comment]
I logged out to test on wayland, and when I logged back in the decode was working (albeit with a terrifying 2GB/s memory leak).  I can't reproduce the issue so far.

**Comment by elFarto** [comment]
AV1 isn't supported at the moment, unfortunately I've just noticed that I didn't comment it out with the rest of the codecs. There is a partial implementation, which is likely what is producing the corrupted image, but it's still missing some logic, and testing.

**Comment by elFarto** [comment]
Closing this issue as AV1 isn't supported at the moment.
