### ISSUE TITLE
VRAM Leak Issue

### ISSUE THREAD

**Issue by Fxzzi** [elFarto/nvidia-vaapi-driver#183]
[This screenshot](https://uploadi.ng/fazzi/9wusuXoW) shows firefox compute process using 5.1gb of GPU memory. This is whilst watching a 1080p video (screenshot of [this video](https://www.youtube.com/watch?v=I4EWvMFj37g&t=47s))

Here are my relevant [environment variables.](https://uploadi.ng/fazzi/GZAMNWOE)

This is also shown in [nvidia-smi](https://uploadi.ng/fazzi/wouxnPG0)

This sometimes reaches the limit of my RTX 3070 which is about 8GB, slowing my computer down to a halt and forcing me to close firefox to get a working desktop back. I am running Wayland with Hyprland, firefox version [110.1.1](https://uploadi.ng/fazzi/LYOjNYm2)

**Comment by elFarto** [comment]
Is it possible for you to capture a log output with NVD_LOG=1 set, while this is happening? We've had issues with the direct backend not freeing memory, but I thought I'd fixed all those issues.
