### ISSUE TITLE
Multi gpus

### ISSUE THREAD

**Issue by Latrolage** [elFarto/nvidia-vaapi-driver#185]
For firefox, env variable LIBVA_DRIVER_NAME needs to be set to nvidia. 

Does this mean it's not possible for firefox to use a certain GPU for a specific set of codecs and then use the nvidia gpu as fallback if the first gpu doesn't support a codec?

**Comment by elFarto** [comment]
Firefox is only capable of using a single GPU for rendering and video decode. Even if it did support it, we can't yet export a DMA-BUF that other GPUs can import (this should be possible to implement, I'm just not sure how yet).

Also, the LIBVA_DRIVER_NAME environment variable isn't required with the latest version of libva installed.
