### ISSUE TITLE
Video stutters when having more than 1 YT videos playing? 

### ISSUE THREAD

**Issue by aw16046** [elFarto/nvidia-vaapi-driver#190]
Anyone else having this issue? For example, having more than 1 firefox application open and both of them playing 4K videos.

Thanks in advance.

**Comment by elFarto** [comment]
I see a few dropped frames with two 4k videos playing, but we've seen that for a while on 4k videos (see #37). I see a lot of dropped frames with three 4k videos playing.

I may be worth seeing how much load your NVDEC engines are under while this is happening, using something like `nvidia-smi pmon` or `nvtop`.

**Comment by elFarto** [comment]
That video does start to drop frames if I open three of them, although it's difficult to notice any major stuttering. They do look a little less smooth than with just one playing.

A 2080Ti should be able to decode three at once without issue.

**Comment by POMATu** [comment]
when i play 4k video my video decoding engine gets utilized to 25% max and thats on RTX 1080. There is no way it can be overloaded with 3 videos.

and I havent seen any stutters so far, maybe few times i heard some click when i start playing or reload page and start playing again like some video engine activation glitch but no stutters during continuous playback
