### ISSUE TITLE
Adding new package dependency for Ubuntu 22.10

### ISSUE THREAD

**Issue by psyer** [elFarto/nvidia-vaapi-driver#192]
Hello, thank you for this great driver. I tried to compile this using the instructions  provided in the readme on Ubuntu 22.10. During the setup run I got the following error from meson.

_meson.build:16:0: ERROR: C shared or static library 'EGL' not found_

I installed the "libegl-dev" Ubuntu package, and this fixed my issue. Just another package dependency for the apt package manager, possibly just for Ubuntu 22.10.

**Comment by elFarto** [comment]
I've updated the readme with this package.
