### ISSUE TITLE
Financial support for the project

### ISSUE THREAD

**Issue by Akkowicz** [elFarto/nvidia-vaapi-driver#20]
Hi,

I'd like to ask if there's any way to financially support you, @elFarto or the project itself.
With your code I was able to finally use the video decoding on my Nvidia card and it significantly improved my experience.

Do you consider setting up some PayPal or Patreon to accept donations? (can be potentially used to finance more recent hardware)

**Comment by elFarto** [comment]
While I appreciate the gesture, it is not necessary. I have a day job that pays the bills, and my reluctance to purchase a new GPU is purely down to not wanting to feed the extortionate prices rather than an inability to.
