### ISSUE TITLE
Is `EGL_PLATFORM=wayland` really needed?

### ISSUE THREAD

**Issue by q234rty** [elFarto/nvidia-vaapi-driver#229]
Looking at https://bugzilla.mozilla.org/show_bug.cgi?id=1769499, it seems that the bug was fixed a long time ago.

Moreover, people seems to be setting this env var globally, which causes issues with Xwayland apps that use EGL, e.g. https://gitlab.gnome.org/GNOME/mutter/-/issues/2793

If it's not longer relevant on FF102+, we could maybe just remove it from the README, or at least mention the fact that setting it globally causes breakage.

**Comment by elFarto** [comment]
That's probably a good idea, I'll update the README.

**Comment by elFarto** [comment]
I just removed it, since we shouldn't actually need it anymore.
