### ISSUE TITLE
Snap firefox build fails while Linux mint firefox build works

### ISSUE THREAD

**Issue by carsonip** [elFarto/nvidia-vaapi-driver#249]
Creating this issue as a PSA.

OS: Linux Mint 21.2

I was previously using the firefox snap from Ubuntu on my Linux Mint. Firefox about:support showed `vaapitest: VA-API test failed: failed to initialise VAAPI connection.` while vainfo was all good. Figured it was something wrong with the snap build. Uninstalled the snap firefox and installed the stock firefox from Linux Mint and it is now all working!

Thanks for the great work.

**Comment by elFarto** [comment]
Yes, snap releases are unable to access this driver since it's outside of the snap. I should probably add something to the README about that.
