### ISSUE TITLE
Question about direct backend

### ISSUE THREAD

**Issue by Tiagoquix** [elFarto/nvidia-vaapi-driver#287]
When using the direct backend, should I set `gfx.x11-egl.force-enabled` to `true` or `false`?

**Comment by elFarto** [comment]
Firefox should already be using EGL as the default backend, so it shouldn't need to be set. You can check this by looking at the `X11_EGL` section in the `about:support` page.

**Comment by nerijus** [comment]
Then README.md should probably be updated that it is not required? Currently it is marked as required.

**Comment by kjkent** [comment]
Yeah I'm currently confused about the same thing -- regardless of Firefox's current default, is it a setting still needing to be set (either by the user or by FF) with the direct backend?
