### ISSUE TITLE
Do you still need nvidia-vaapi-driver for Firefox if using Zink Vulkan ?

### ISSUE THREAD

**Issue by brokeDude2901** [elFarto/nvidia-vaapi-driver#302]
I've compiled and installed the latest `nvidia-vaapi-driver`
After I installed `nvidia-driver-555` from the `ubuntu-graphics-drivers` PPA:
![image](https://github.com/elFarto/nvidia-vaapi-driver/assets/46110534/6d40a802-fc8e-4fdf-b353-c58ef6da9d6d)

`nvidia-smi` show `C+G` for `firefox`, watching a VP9 4K Youtube and CPU Usage only hover around 10%, but `nvidia-smi dmon` show no decoding activity:
![image](https://github.com/elFarto/nvidia-vaapi-driver/assets/46110534/4fc72e5f-32e8-4cfa-a541-e8bca63452c6)
![image](https://github.com/elFarto/nvidia-vaapi-driver/assets/46110534/347f7b61-e733-4417-bbfd-b6a143a47470)

Firefox `about:support` shows:
![image](https://github.com/elFarto/nvidia-vaapi-driver/assets/46110534/2c51c270-7f73-4976-a0ae-4e102db6dba1)
![image](https://github.com/elFarto/nvidia-vaapi-driver/assets/46110534/99982248-bfd3-4319-aa8f-1e59cec00d25)

Watching a local .mp4 H264 with Ubuntu Totem still shows GPU decoding works in `nvidia-smi dmon`:
![image](https://github.com/elFarto/nvidia-vaapi-driver/assets/46110534/f487965b-2fbb-4322-b3b2-6eff269e86c2)
![image](https://github.com/elFarto/nvidia-vaapi-driver/assets/46110534/f0ffecd8-1861-41df-8874-5de340d225d9)
Open that same .mp4 H264 with Firefox, the video plays smoothly with little to no CPU usage, but no GPU decode activity in 'nvidia-smi dmon'

So does Zink Vulkan actually decode VP9/H264 stuff in Firefox now, because there is so little CPU usage watching 4K video in Firefox. Anybody know what is going on ?

**Comment by ManuLinares** [comment]
You are not using nvidia-vaapi-driver, probably you haven't configured it correctly with firefox.

You are using software decoding.
