### ISSUE TITLE
Videos occasionally skip several seconds

### ISSUE THREAD

**Issue by phonetic112** [elFarto/nvidia-vaapi-driver#306]
On YouTube, videos occasionally skip forward several seconds. I've only observed this with VP9 so far. Using an RTX 4070 and Firefox.

**Comment by Clutchnp** [comment]
@phonetic112 Can confirm , I am currently also testing with avc1 which is not giving me problems for now

**Comment by Clutchnp** [comment]
Update: This dosen't seem like a hardware acceleration issue on my end , if youtube videos are not accelerated on firefox this still happens,whereas on chomium based browsers, this dosen't happen because default codec youtube sends on those browsers is av1. Whereas Firefox receives vp9 by default.

**Comment by phonetic112** [comment]
you're right, I can repro with software decoding as well. I'll close this then
