### ISSUE TITLE
Is MOZ_DISABLE_RDD_SANDBOX=1 still required?

### ISSUE THREAD

**Issue by Tiagoquix** [elFarto/nvidia-vaapi-driver#307]
It seems this env. variable is no longer required as of Firefox version 102.

Relevant links:

https://bugzilla.mozilla.org/show_bug.cgi?id=1751363

https://bugzilla.mozilla.org/show_bug.cgi?id=1610199

https://www.mozilla.org/en-US/firefox/102.0/releasenotes/ (https://bugzilla.mozilla.org/show_bug.cgi?id=1722051)

**Comment by elFarto** [comment]
It's still required, and likely always will be. NVDEC/CUDA is not designed to be run inside a sandboxed environment.
