### ISSUE TITLE
Install instruction contradictions

### ISSUE THREAD

**Issue by S7venLights** [elFarto/nvidia-vaapi-driver#320]
Under https://github.com/elFarto/nvidia-vaapi-driver/#upstream-regressions
you say:
The EGL backend is broken on driver versions 525 or later due to a regression. Users running these drivers should use the [direct backend](https://github.com/elFarto/nvidia-vaapi-driver/#direct-backend) instead.

In [firefox config](https://github.com/elFarto/nvidia-vaapi-driver/#firefox) you say:
gfx.x11-egl.force-enabled 	true 	Required, this driver requires that Firefox use the EGL backend. It may be enabled by default. It is recommended to test it with the MOZ_X11_EGL=1 environment variable before enabling it in the Firefox configuration.

Should one not set gfx.x11-egl.force-enabled  to true?

**Comment by elFarto** [comment]
Firefox still needs to use EGL to import frames, but this driver can't use it's EGL/EGLStreams backend to export frames. They are two separate uses of EGL.
