### ISSUE TITLE
AV1 8K stop working at 60 fps

### ISSUE THREAD

**Issue by RobertoAlda** [elFarto/nvidia-vaapi-driver#333]
Hi,

my system is:
Ubuntu Desktop 24.04.01 LTS
Nvidia RTX 4000 SFF Ada Generation 20Gb  (supports AV1 HW decoding)
Nvidia  Driver Version: 550.107.02
FIrefox Nightly  132.0a1 (2024-09-22) (64-bit)
Firefox flag:media.av1.enabled=true

when i play video 4k/8k at 30 or 60fps H264,VP9 i have no problem at all, nvidia hw acceleration works well,
instead when i play AV1 files they works well at 4k 30/60fps and 8k 30fps, 
but with **AV1 8K 60 fps** after few seconds the nvidia hw acceleration sopts working and the load move to the CPU causing stuttering.

The sample video used has 77Mb/s of video bitrate , color space YUV 420.

Is an nvidia-vaapi-driver issue or a FIrefox issue?

Thank you.

**Comment by elFarto** [comment]
This is a Firefox issue as far as I know. Firefox attempts to detect if the hardware isn't quick enough to keep up, however the way Firefox is using VA-API isn't efficient enough for high bitrate videos.

I would suggest raising this as an issue in the Firefox bugzilla.
