### ISSUE TITLE
more small vid chroma error regions even without single plane

### ISSUE THREAD

**Issue by rakslice** [elFarto/nvidia-vaapi-driver#344]
Just found another video that is still giving a similar looking missing chroma region with current master 9c4a3c70b68467343262d295ce56a56d510ec342:
https://t.gifs.bsky.app/qgTXJF6Bgz0AAAP3/jeff-the-land-shark-marvel-rivals.webm
(vp8, 214x172)

![master same frame Screenshot from 2024-12-19 17-30-58](https://github.com/user-attachments/assets/fe822d4c-c37d-418a-876e-e3a6abe0413c)

_Originally posted by @rakslice in https://github.com/elFarto/nvidia-vaapi-driver/issues/340#issuecomment-2556079238_

**Comment by rakslice** [comment]
Another:
https://t.gifs.bsky.app/C90CNOkocIIAAAP3/serious-seriously.webm

Also height 172 (-> chroma 86)

**Comment by rakslice** [comment]
Using `log2GobsPerBlockY` 3 for these works.

**Comment by ToadKing** [comment]
Another example if it helps: https://t.gifs.bsky.app/VKre7tEUsssAAAP3/my-cousin-vinny-shocking.webm
