### ISSUE TITLE
Video might crash after returning to a suspended tab

### ISSUE THREAD

**Issue by guihkx** [elFarto/nvidia-vaapi-driver#44]
Firefox seems to suspend background tabs playing videos after 30 seconds or so, so upon returning to such tab, the video sometimes crashes.

Log: https://gist.githubusercontent.com/guihkx/2cfa9d5131ba801e55b3d873add760fa/raw/c91e345428b47939eafb515eb278cbdaa271014a/log.txt

Video for repro:

https://www.youtube.com/watch?v=RoVKSAuX9r8

- OS: Arch Linux
- NVIDIA VAAPI Driver version: 85e45bd
- GPU: GTX 660 (driver version: 470.94)
- Firefox 96.0.2

**Comment by elFarto** [comment]
I think that might be an issue with the latest commit, try rolling back to commit: 71f2e0a for the moment. It seems to be trying initalising the driver 3 or 4 times and breaking it.

**Comment by elFarto** [comment]
Spotted the issue. I haven't seen Firefox destroy the context, but not terminate the library before. This left all the surfaces we were counting still around, and these got added to the new surfaces. Trying to allocate 50 1080p surfaces was breaking it.

**Comment by guihkx** [comment]
Thank you for this project, you're my hero. <3
