### ISSUE TITLE
High RAM usage and frame drops in Firefox

### ISSUE THREAD

**Issue by mustafademiral** [elFarto/nvidia-vaapi-driver#48]
Firstly thank you for the driver. This is a very good project. 

- OS: Arch
- Kernel: 5.16.2
- Display Server: X11
- Firefox Ver: 96.0.2
- Driver: nvidia 495.46-10
- GPU: GTX1050Ti [Desktop]

Test video: https://youtu.be/BGGs3a_DbPw

1th minute of video: 1.64 GB RAM usage
12th minute of video: 4.06 GB RAM usage

Frame drops and video details: 
![youtube-inf](https://user-images.githubusercontent.com/82894612/151534611-5bce56a7-a8df-47e9-aa80-4fdc235bf404.png)
Nvidia-smi output in 12th minute of video:
![nvidia-smi](https://user-images.githubusercontent.com/82894612/151534785-a6cb459c-4169-4181-bd29-5418246e3b35.png)
Nvidia Log: https://gist.githubusercontent.com/mustafademiral/4a75679bf21d7034a7ce099a0b4fb533/raw/36d7e91bcde96378e949294ad86fe34e53be9d97/gistfile1.txt

  ```
  $vainfo
vainfo: VA-API version: 1.13 (libva 2.13.0)
vainfo: Driver version: VA-API NVDEC driver
vainfo: Supported profile and entrypoints
      VAProfileMPEG2Simple            :	VAEntrypointVLD
      VAProfileMPEG2Main              :	VAEntrypointVLD
      VAProfileVC1Simple              :	VAEntrypointVLD
      VAProfileVC1Main                :	VAEntrypointVLD
      VAProfileVC1Advanced            :	VAEntrypointVLD
      <unknown profile>               :	VAEntrypointVLD
      VAProfileH264Main               :	VAEntrypointVLD
      VAProfileH264High               :	VAEntrypointVLD
      VAProfileH264ConstrainedBaseline:	VAEntrypointVLD
      VAProfileHEVCMain               :	VAEntrypointVLD
      VAProfileVP9Profile0            :	VAEntrypointVLD

  ```
  ```
$cat /proc/cmdline
BOOT_IMAGE=/boot/vmlinuz-linux root=UUID=20a39f93-61e4-4ef4-a033-107c400af242 rw loglevel=3 quiet nvidia-drm.modeset=1 nvidia nvidia_modeset nvidia_uvm nvidia_drm

  ```

**Comment by elFarto** [comment]
By increasing memory usage, are you referring to VRAM or system RAM? Your screenshot suggests that the video decode is using about 500MB of VRAM at the 12th minute (the firefox process with type 'c'), which is about what I would expect for a 4k video.

The dropped frames are an ongoing issue, however we're not entirely sure where they're happening. I done captures of firefox where the Youtube player says it's dropped frames, but firefox says it hasn't.

**Comment by mustafademiral** [comment]
Sorry i referring to system RAM. When i continue watch video, RAM usage can reach up to 6-7GB. Frame drops increase with RAM usage. 
![htop](https://user-images.githubusercontent.com/82894612/151540155-e4d6409c-ef8a-41df-a636-bcce9de58a04.png)

**Comment by elFarto** [comment]
The memory usage is probably related to this Firefox issue: [1743750](https://bugzilla.mozilla.org/show_bug.cgi?id=1743750)

**Comment by joebonrichie** [comment]
I´d also try setting `media.ffvpx.enabled` to false in about:config - video decoding should still work.

**Comment by mustafademiral** [comment]
> The memory usage is probably related to this Firefox issue: [1743750](https://bugzilla.mozilla.org/show_bug.cgi?id=1743750). Looks like there's some nightly builds available with that fix in which you could test with.

Yes i tried in nightly build and problem fixed and frame drops lesser. 

> I´d also try setting `media.ffvpx.enabled` to false in about:config - video decoding should still work.

Also that fixed RAM usage in stable version. 

Thank you for your helps.
