### ISSUE TITLE
144p VP9 renders incorrectly

### ISSUE THREAD

**Issue by aleasto** [elFarto/nvidia-vaapi-driver#49]
![image](https://user-images.githubusercontent.com/8167495/151973443-acd2c9dd-8600-4da0-9a83-b55b66376366.png)

**Comment by elFarto** [comment]
This is a know issue with Firefox, issue [1750389](https://bugzilla.mozilla.org/show_bug.cgi?id=1750389). This has already been fixed, and should be in Firefox 98.

**Comment by aleasto** [comment]
Cool, thanks
