### ISSUE TITLE
Unknown options: "av1"

### ISSUE THREAD

**Issue by Munzu** [elFarto/nvidia-vaapi-driver#54]
I'm using the AUR git-version package of this driver. I'm not sure if this is an error with the driver or with the AUR package but I'm getting the following error when I tried to update my system:

```
meson.build:1:0: ERROR: Unknown options: "av1"

A full log can be found at /home/tai/.cache/paru/clone/nvidia-vaapi-driver-git/src/nvidia-vaapi-driver/build/meson-logs/meson-log.txt
==> ERROR: A failure occurred in prepare().
    Aborting...
error: failed to build 'nvidia-vaapi-driver-git-0.0.2.r10.gf5924d5-1': 

error: packages failed to build: nvidia-vaapi-driver-git-0.0.2.r10.gf5924d5-1
```

It worked fine last night.

Here's the log:
[meson-log.txt](https://github.com/elFarto/nvidia-vaapi-driver/files/8010060/meson-log.txt)

- Arch
- Kernel 5.16.5-arch1-1 
- GTX 970
- Proprietary driver version 510.47.03
- X11
- KDE Plasma
- Firefox 96.0.3
- `cat /sys/module/nvidia_drm/parameters/modeset` gives Y
- I have configured the Firefox options as described in the README, excluding the last one which doesn't apply to my GPU driver version

**Comment by elFarto** [comment]
I've just removed that option, and enabled AV1 by default so it's no longer required to pass that option in.

**Comment by Munzu** [comment]
Oh my bad, I should have looked first. Others have reported it on the AUR already. Sorry about that. Thanks, I'm closing this.

**Comment by eli-schwartz** [comment]
It is possible to keep the option in meson_options.txt, but warn when users try to define it.

https://mesonbuild.com/Build-options.html#deprecated-options

**Comment by elFarto** [comment]
Is there any particular reason to keep it? There are very few people using it, and the AUR has already been updated.

**Comment by eli-schwartz** [comment]
The capability is there in case people want it. Largely because there are people that actually do want to do staged deprecation followed by removal across multiple releases.

So basically, if you have to ask whether it's worth it then you probably don't want it. That's fine too. :)
