### ISSUE TITLE
Is it possible to make video hardware acceleration in Google Chrome with your driver?

### ISSUE THREAD

**Issue by ZERONIGT** [elFarto/nvidia-vaapi-driver#56]
Is it possible to make video hardware acceleration in Google Chrome with your driver? If so, how?

**Comment by elFarto** [comment]
No, not at the moment. Chrome is difficult to get the driver working with as it relies on a lot of things the NVIDIA driver doesn't support. In addition, it's extremely flaky in anything other than the default configuration on my PC. We're tracking this in issue #5.
