### ISSUE TITLE
Video playback green with multiple NVIDIA GPU's, single GPU works

### ISSUE THREAD

**Issue by ASeagullFan** [elFarto/nvidia-vaapi-driver#60]
First time posting an issue to a bug tracker. Thank you for your work. :)

Firefox 97.0.1
Manjaro 21.2.2
GPU Configuration: 1080Ti (Display) / 3060Ti (Compute)
Screenshots and logs are from Wayland, but also happens with X11.

Video plays green with multiple GPU's attached

![Screenshot from 2022-02-22 09-57-36](https://user-images.githubusercontent.com/100180515/155064767-76197084-703b-45ec-bbbe-3660738bd9a6.png)

After isolating the 3060Ti by binding it to vfio at boot, thus making the 1080Ti the only visible GPU

![Screenshot from 2022-02-22 10-06-50](https://user-images.githubusercontent.com/100180515/155064872-24d12673-2e47-45b4-9cff-8558b5ca6426.png)

Logs

[NVD.log](https://github.com/elFarto/nvidia-vaapi-driver/files/8113712/NVD.log) [Multi GPU]

[NVD_single.log](https://github.com/elFarto/nvidia-vaapi-driver/files/8113715/NVD_single.log) [Single GPU]

Thanks.

**Comment by elFarto** [comment]
It looks like it's picking the 'wrong' device. The driver is hardcoded to pick CUDA device 0, and it looks like the GPU Firefox is using is device 1. I'll see if I can add an environment variable to control that.

**Comment by elFarto** [comment]
That was easier than I thought. I've push a fix to master that adds the `NVD_GPU` environment variable. Try setting that to `1` and see if that fixes your issue.

This isn't the proper solution for the issue. The proper solution would be to use the device that VA-API passes to us. However that's complicated by the fact we still need LIBVA_DRIVER_NAME set, which could lead to being initialised on a different GPU. Hopefully this hack should suffice for the short term.

**Comment by ASeagullFan** [comment]
Thank you. That has fixed the issue. ❤️

**Comment by elFarto** [comment]
Hey, I've finally got around to making the proper fix. Could you retest using the latest commit and see if it works without the NVD_GPU variable set?

**Comment by elFarto** [comment]
Thanks for that, and the log file. That looks to be doing exactly what I wanted.
