### ISSUE TITLE
Vainfo fails with cuda error 'unknown error' (999)

### ISSUE THREAD

**Issue by JustCauseWhyNot** [elFarto/nvidia-vaapi-driver#88]
I've got nvidia-vaapi-driver 0.6 installed, and environmental variable LIBVA_DRIVER_NAME=nvdec. This is the output vainfo gives me 
`libva info: VA-API version 1.14.0` 
`libva info: User environment variable requested driver 'nvdec'`
`libva info: Trying to open /usr/lib64/va/drivers/nvdec_drv_video.so`

**Comment by elFarto** [comment]
The default driver name is `nvidia`, not `nvdec`.

**Comment by JustCauseWhyNot** [comment]
I'm aware but installing this through an [ebuild](https://gpo.zugaina.org/AJAX/Ebuild/53628758/View) on gentoo the driver is /usr/lib64/va/drivers/nvdec_drv_video.so.

This is the output of vainfo if LIBVA_DRIVER_NAME=nvidia is.
`libva info: VA-API version 1.14.0`
`libva info: User environment variable requested driver 'nvidia'`
`libva info: Trying to open /usr/lib64/va/drivers/nvidia_drv_video.so`
`libva info: va_openDriver() returns -1`
`vaInitialize failed with error code -1 (unknown libva error),exit`

**Comment by elFarto** [comment]
Ok, that's fine. Can you run `NVD_LOG=1 vainfo` and paste the output here?

**Comment by JustCauseWhyNot** [comment]
❯ NVD_LOG=1 vainfo
libva info: VA-API version 1.14.0
libva info: User environment variable requested driver 'nvidia'
libva info: Trying to open /usr/lib64/va/drivers/nvidia_drv_video.so
libva info: va_openDriver() returns -1
vaInitialize failed with error code -1 (unknown libva error),exit.

Do I need to do something different?

**Comment by elFarto** [comment]
You'll need to put the LIBVA_DRIVER_NAME variable back to nvdec.

**Comment by JustCauseWhyNot** [comment]
❯ NVD_LOG=1 vainfo
libva info: VA-API version 1.14.0
libva info: User environment variable requested driver 'nvidia'
libva info: Trying to open /usr/lib64/va/drivers/nvidia_drv_video.so
libva info: va_openDriver() returns -1
vaInitialize failed with error code -1 (unknown libva error),exit

> You'll need to put the LIBVA_DRIVER_NAME variable back to nvdec.
I goofed that. thanks for the reminder.

**Comment by elFarto** [comment]
Can you paste the output of `lsmod | grep nvidia`?

**Comment by JustCauseWhyNot** [comment]
❯ lsmod | rg nvidia
nvidia_uvm           1150976  0
nvidia_drm             61440  3
nvidia_modeset       1097728  5 nvidia_drm
nvidia              40165376  256 nvidia_uvm,nvidia_modeset

**Comment by elFarto** [comment]
Hmm, not sure what's going on here. I've only seen a 999 error early on when the nvidia_uvm module wasn't loaded, but yours is. You can try running vainfo as root (either directly or using sudo), which might fix it if there's something not configured correctly on your install.

**Comment by JustCauseWhyNot** [comment]
❯ NVD_LOG=1 doas vainfo
libva info: VA-API version 1.14.0
libva info: User environment variable requested driver 'nvdec'
libva info: Trying to open /usr/lib64/va/drivers/nvdec_drv_video.so
      4444.065192957 [10231-10231] ../nvidia-vaapi-driver-0.0.6/src/vabackend.c:  99                     init cuda error 'unknown error' (999)

❯ NVD_LOG=1 vainfo
libva info: VA-API version 1.14.0
libva info: User environment variable requested driver 'nvdec'
libva info: Trying to open /usr/lib64/va/drivers/nvdec_drv_video.so
      4450.539636054 [10248-10248] ../nvidia-vaapi-driver-0.0.6/src/vabackend.c:  99                     init cuda error 'unknown error' (999)

Here's vainfo output with doas vs not running with doas.

**Comment by elFarto** [comment]
I'm starting to run out of ideas. One last one, can you check if you have `nvidia-modprobe` installed, and that it has the SUID bit set (yours might be in a different place):
```
> ls -l /usr/bin/nvidia-modprobe
-rwsr-xr-x 1 root root 32648 May 31 20:23 /usr/bin/nvidia-modprobe*
```

**Comment by JustCauseWhyNot** [comment]
❯ ls -l /usr/bin/nvidia-modprobe
-rws--x--- 1 root video 39320 Jun  2 12:12 /usr/bin/nvidia-modprobe

**Comment by JustCauseWhyNot** [comment]
❯ ls -l /usr/bin/nvidia-modprobe
-rwxr-xr-x 1 root root 39320 Jun  2 12:12 /usr/bin/nvidia-modprobe
❯ NVD_LOG=1 vainfo
libva info: VA-API version 1.14.0
libva info: User environment variable requested driver 'nvdec'
libva info: Trying to open /usr/lib64/va/drivers/nvdec_drv_video.so
      5442.102619946 [11673-11673] ../nvidia-vaapi-driver-0.0.6/src/vabackend.c:  99                     init cuda error 'unknown error' (999)

That's the output I get after running commands. I appreciate your help.

**Comment by elFarto** [comment]
Looks like it lost the sticky bit, do `chmod +s /usr/bin/nvidia-modprobe` to fix it.

**Comment by elFarto** [comment]
I'm out of ideas for the moment. You can try searching around for other people having issues with 'CUDA init error 999'. Potentially you could run `vainfo` under `strace` to see what the last failed command is (if any), and hope that points you in the right direction.

**Comment by JustCauseWhyNot** [comment]
I've done some screwing around, and this is my out put.

❯ NVD_LOG=1 vainfo
libva info: VA-API version 1.14.0
libva info: User environment variable requested driver 'nvdec'
libva info: Trying to open /usr/lib64/va/drivers/nvdec_drv_video.so
       167.172356022 [4151-4151] ../nvidia-vaapi-driver-0.0.6/src/vabackend.c:  99                     init cuda error 'initialization error' (3)

**Comment by JustCauseWhyNot** [comment]
I've found the causation of this error. It's got something to do with one of these kernel module paramaters.

  1 >--NVreg_EnableMSI=1 \
  2 >--NVreg_EnablePCIeGen3=1 \
  3 >--NVreg_InitializeSystemMemoryAllocations=0 \
  4 >--NVreg_UsePageAttributeTable=1 \
  5 >--NVreg_DynamicPowerManagement=0x00
