### ISSUE TITLE
Huge watt when docoding

### ISSUE THREAD

**Issue by linzj** [elFarto/nvidia-vaapi-driver#93]
When decoding using nvidia-vaapi, which actually working on NVDEC, consume 108 watt decoding a 4K HEVC.
Or 38 watt if using VDPAU.

Maybe we should consider briding on VDPAU not NVDEC?

**Comment by philipl** [comment]
Covered in #74, but yes, the cuda requirement forces the GPU into a high power level. vdpau doesn't have any way to do efficient interop for surface export, which is why it can't be used for the implementation.

**Comment by linzj** [comment]
Thanks for the reply and I have checked vdpau API，I understood the point you have mentioned.I think this is the point  VDpau is missing.

**Comment by linzj** [comment]
Nothing we can do here so i closed the issue
